### ISSUE TITLE
caddy not working after install caddy with ipfilter extension

### ISSUE THREAD

**Issue by d-arnab** [pyed/ipfilter#25]
Hi ,
after downloading caddy from below link
curl https://getcaddy.com | bash -s personal http.filter
using personal license
i add below code in Caddy file
ipfilter /test.zigfo.com {
        rule allow
        ip 192.168.0.1
}
after adding it when i'm restarting caddy its terminated
what i want is to allow the test.zigfo.com sub domain only with specific IP
can any one please tell me where i'm mking mistake?

**Comment by pyed** [comment]
Ipfilter doesn’t support subdomains. I’m not sure of the best way of doing that. PRs are welcome

**Comment by d-arnab** [comment]
then is there any another process to do it? if any could you please explain? thanks

**Comment by pyed** [comment]
Maybe running an independent instance of caddy for this domain would work

**Comment by krader1961** [comment]
This question appears to be due to a misunderstanding of how Caddy and this plugin works. The argument which follows `ipfilter` is not a FQDN. It is a URL path independent of the target host name. What you are asking for is a way to predicate the ipfilter rule on the `{hostonly}` placeholder (or the equivalent Caddy internal variable).

Personally I don't think this is the responsibility of the `ipfilter` plugin. It can be handled by the existing Caddy directives (e.g., `rewrite`).
