### ISSUE TITLE
Is it possible to specify CIDR range in prefix_dir ?

### ISSUE THREAD

**Issue by sebastientaggart** [pyed/ipfilter#36]
Since CIDR ranges look like directories, how would this work (if it's possible)?

**Comment by pyed** [comment]
'prefix_dir' doesn't support ranges, if you have that many ranges where have them in your config file would clutter it, and you really wanna use the 'prefix_dir', you could write a script that generate files from CIDR ranges that satisfies the rules of 'prefix_dir', maybe @krader1961 has some insights.

**Comment by sebastientaggart** [comment]
Got it!  I actually went ahead and wrote a bash script to do this: https://gist.github.com/sebastientaggart/491ad1c8b0b92d1b91de76859c7ddd24  Feel free to include it or some version if that's helpful.

**Comment by krader1961** [comment]
What @pyed said. The idea behind `prefix_dir` is to use the filesystem as a cheap way to test if a "key" (a given IP address) exists. So that blocking or whitelisting a specific address is as simple as `touch $prefix_dir/$ip_addr`. Although that would normally be done by a program that monitors the requests handled by the web server. For example, by reading the caddy log file and blacklisting abusive IP addrs in real-time. Storing arbitrary CIDR ranges would require a considerably more complex implementation that would negate the primary goal. For CIDR ranges the `ip` directive should be used.
