### ISSUE TITLE
Howto filter IP subnets

### ISSUE THREAD

**Issue by vaLinBSD** [pyed/ipfilter#9]
Howto filter ip subnets, for example 10.0.0.0/8 ?
All my attempts ends with 'Parse error: ipfilter: Can't parse IPv4 address'

**Comment by andybeesee** [comment]
I was just looking in to this as well. It doesn't seem possible right now.

Based on what I see in the [code](https://github.com/pyed/ipfilter/blob/master/ipfilter.go) only the last part of the IP is swapped. 

```go
// split the start of the range on "." and switch the last field with splitted[1], e.g 1.1.1.1 -> 1.1.1.10
fields := strings.Split(start.String(), ".")
```

**Comment by pyed** [comment]
@andybeesee that's correct, currently it doesn't support the CIDR notion, just simple ranges, e.g. `10.0.0.0-255`

**Comment by andybeesee** [comment]
Do you think the way [apache](https://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#require) handles it would be a reasonable way to approach the problem (assuming you think it is a problem worth solving)? 

Rather than `10.0.0.0/8` you could just define `10`, to open everything from `10.0.0.0` to `10.255.255.255`. For my needs I only want to block external access to a specific subdomain, so I just want to be able enter `192.168`

Apache docs give this example: 
```
Require ip 10 172.20 192.168.2
```

**Comment by pyed** [comment]
That's neat, I'll have a look at it later today, thanks

**Comment by vaLinBSD** [comment]
That would be great guys! Thnx

**Comment by pyed** [comment]
well this is a bit late, I added support for open ranges just the way @andybeesee described, I would like to get some code review: https://github.com/pyed/ipfilter/blob/openRange/ipfilter.go#L255 to L274

**Comment by andybeesee** [comment]
Sorry I can't be more help here, I have written about 0 lines of Go code.

**Comment by pyed** [comment]
https://github.com/pyed/ipfilter/pull/10
